baseurl = "http://mpowered-consulting.github.io/"
languageCode = "en-us"
title = "purehugo"
theme = "purehugo"
Paginate = 10
disqusShortname = "xxxx"

[params]
  twitterName = "dragos_plesca"
  githubName = "dplesca"
  stackOverflowId = "#######"
  linkedinName = "dragos-plesca-52797444"
  description = "Demo site for a hugo theme"
  google_analytics = "UA-xxxxxx-xx"
